import './lib/compat';
import {createRoot} from 'react-dom/client';
import {MemoryRoom} from './components/MemoryRoom';
import './styles/base.css';
import './styles/room.css';
import './styles/memories.css';
import './styles/ending.css';
import './styles/camera.css';
import './styles/spatial.css';
import './styles/refinements.css';
import './styles/call.css';
import './styles/portable.css';
import './styles/polish.css';
createRoot(document.getElementById('root')!).render(<MemoryRoom/>);
